<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>Avi</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Avi</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.barteiks.avi</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>MSIX</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
	  <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	  <AndroidUseAapt2>True</AndroidUseAapt2>
	  <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
		<AndroidPackageFormat>aab</AndroidPackageFormat>
		<AndroidUseAapt2>True</AndroidUseAapt2>
		<AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
	</PropertyGroup>

	<PropertyGroup>
	  <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
	  <DefaultLanguage>en</DefaultLanguage>
	  <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
	  <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
	  <PackageCertificateThumbprint>D40A8186CC159F9FC4B86BBA2F483EFEE1742FAC</PackageCertificateThumbprint>
	  <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
	  <AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
	  <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
	  <GenerateTestArtifacts>False</GenerateTestArtifacts>
	  <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Resources\Raw\Assets\chatHistory.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\Raw\Assets\json.gbnf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\Raw\Assets\promptMain.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui.Core" Version="14.1.1" />
		<PackageReference Include="LLamaSharp" Version="0.27.0" />
		<PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.27.0" />
		<PackageReference Include="LLamaSharp.Backend.Cpu.Android" Version="0.27.0" />
		<PackageReference Include="LLamaSharp.Backend.Cuda12" Version="0.27.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.60" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />
		<PackageReference Include="NAudio" Version="2.3.0" />
		<PackageReference Include="NAudio.Core" Version="2.3.0" />
		<PackageReference Include="SkiaSharp" Version="3.119.2" />
		<PackageReference Include="SkiaSharp.Views" Version="3.119.2" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.119.2" />
		<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="3.119.2" />
		<PackageReference Include="Whisper.net" Version="1.9.0" />
		<PackageReference Include="Whisper.net.Runtime" Version="1.9.0" />
		
	</ItemGroup>
	<!-- ANDROID --><!--
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
		<PackageReference Include="LLamaSharp" Version="0.24.0" />
		<PackageReference Include="LLamaSharp.Backend.Cpu.Android" Version="0.24.0" />
	</ItemGroup>

	--><!-- WINDOWS --><!--
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
		<PackageReference Include="LLamaSharp" Version="0.26.0" />
		<PackageReference Include="LLamaSharp.Backend.Cuda12" Version="0.26.0" />
	</ItemGroup>

	--><!-- IOS --><!--
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
		<PackageReference Include="LLamaSharp" Version="0.26.0" />
		<PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.26.0" />
	</ItemGroup>

	--><!-- MACCATALYST --><!--
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-maccatalyst'">
		<PackageReference Include="LLamaSharp" Version="0.26.0" />
		<PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.26.0" />
	</ItemGroup>-->
	
	<ItemGroup>
	  <Compile Update="UI\MainWindow.xaml.cs">
	    <DependentUpon>MainWindow.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Platforms\Android\SpeechRecognition.cs">
	    <ExcludeFromCurrentConfiguration>true</ExcludeFromCurrentConfiguration>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <MauiXaml Update="UI\MainWindow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="UI\Controls\SettingsItem.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="UI\SettingsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
